--- #YAML:1.0
name:               Rose-Object
version:            0.855
abstract:           A simple object base class.
author:
    - John Siracusa <siracusa@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:          5.006000
    Test::More:    0
    Test::Simple:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=Rose-Object
    homepage:    http://rose.googlecode.com/
    license:     http://dev.perl.org/licenses/
    repository:  http://rose.googlecode.com/svn/trunk/modules/Rose-Object
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
