---
abstract: 'A simple object base class.'
author:
  - 'John Siracusa <siracusa@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rose-Object
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
  Test::Simple: 0
  perl: 5.006000
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Rose-Object
  homepage: http://rose.googlecode.com/
  license: http://dev.perl.org/licenses/
  repository: http://rose.googlecode.com/svn/trunk/modules/Rose-Object
version: 0.860
